use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Up,
    Down,
    Left,
    Right,
    Enter,
    Escape,
    Quit,
    PlayPause,
    Next,
    Prev,
    VolumeUp,
    VolumeDown,
    SeekForward,
    SeekBackward,
    ToggleShuffle,
    ToggleRepeat,
    Search,
    Delete,
    Like,
    ScrollUp,
    ScrollDown,
    Tab,
    BackTab,
    Reload,
    Help,
    Resize(u16, u16),
    ToggleLibraryView,
    NowPlaying,
    QueueView,
    PlayAll,
    AddToQueue,
    GoBack,
    Confirm,
    Cancel,
    Char(char),
    PageDown,
    PageUp,
}

impl Action {
    pub fn from_key(key: KeyEvent, vim_keys: bool) -> Option<Action> {
        match key.code {
            KeyCode::Char('q') if vim_keys => None,
            KeyCode::Char('q') => Some(Action::Quit),
            KeyCode::Char('c') if key.modifiers == KeyModifiers::CONTROL => Some(Action::Quit),
            KeyCode::Char('d') if key.modifiers == KeyModifiers::CONTROL => Some(Action::ScrollDown),
            KeyCode::Char('u') if key.modifiers == KeyModifiers::CONTROL => Some(Action::ScrollUp),
            KeyCode::Esc => Some(Action::Escape),
            KeyCode::Enter => Some(Action::Enter),
            KeyCode::Tab => Some(Action::Tab),
            KeyCode::BackTab => Some(Action::BackTab),
            KeyCode::Backspace => Some(Action::GoBack),
            KeyCode::Delete => Some(Action::Delete),
            KeyCode::Home => Some(Action::ScrollUp),
            KeyCode::End => Some(Action::ScrollDown),
            KeyCode::PageUp => Some(Action::PageUp),
            KeyCode::PageDown => Some(Action::PageDown),
            KeyCode::Up => Some(Action::Up),
            KeyCode::Down => Some(Action::Down),
            KeyCode::Left => Some(Action::Left),
            KeyCode::Right => Some(Action::Right),
            KeyCode::Char('j') if vim_keys => Some(Action::Down),
            KeyCode::Char('k') if vim_keys => Some(Action::Up),
            KeyCode::Char('h') if vim_keys => Some(Action::Left),
            KeyCode::Char('l') if vim_keys => Some(Action::Right),
            KeyCode::Char('/') => Some(Action::Search),
            KeyCode::Char(',') => Some(Action::SeekBackward),
            KeyCode::Char('.') => Some(Action::SeekForward),
            KeyCode::Char(' ') => Some(Action::PlayPause),
            KeyCode::Char('?') => Some(Action::Help),
            KeyCode::Char('+') => Some(Action::VolumeUp),
            KeyCode::Char('-') => Some(Action::VolumeDown),
            KeyCode::Char('n') => Some(Action::Next),
            KeyCode::Char('p') => Some(Action::Prev),
            KeyCode::Char('s') => Some(Action::ToggleShuffle),
            KeyCode::Char('r') => Some(Action::ToggleRepeat),
            KeyCode::Char('z' | 'L') => Some(Action::NowPlaying),
            KeyCode::Char('a') => Some(Action::PlayAll),
            KeyCode::F(1) => Some(Action::Help),
            KeyCode::Char(c) => Some(Action::Char(c)),
            _ => None,
        }
    }

    /// Key mapping for text input (search): printable characters go into
    /// the query instead of being intercepted as player commands.
    pub fn from_key_text_input(key: KeyEvent) -> Option<Action> {
        match key.code {
            KeyCode::Char('c') if key.modifiers == KeyModifiers::CONTROL => Some(Action::Quit),
            KeyCode::Esc => Some(Action::Escape),
            KeyCode::Enter => Some(Action::Enter),
            KeyCode::Backspace => Some(Action::GoBack),
            KeyCode::Up => Some(Action::Up),
            KeyCode::Down => Some(Action::Down),
            KeyCode::PageUp => Some(Action::PageUp),
            KeyCode::PageDown => Some(Action::PageDown),
            KeyCode::Char(c) => Some(Action::Char(c)),
            _ => None,
        }
    }
}